on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
jobs:
  build-release:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout PKGBUILD file
        uses: actions/checkout@v4.2.0
        with:
          repository: DeltaCopy/lightly-archlinux
      - name: System update
        run: pacman -Syu --noconfirm
      - name: Install sudo, git and compile dependencies
        run: |
          pacman -Sy sudo git binutils make gcc pkg-config fakeroot \
          cmake extra-cmake-modules \
          kdecoration qt6-declarative kcoreaddons \
          kcmutils kcolorscheme kconfig kguiaddons \
          kiconthemes kwindowsystem --noconfirm
      - name: Setup build user
        run: |
          useradd builduser -m # Create the builduser
          passwd -d builduser # Delete the buildusers password
          printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # Allow the builduser passwordless sudo
      - name: Update PKGBUILD file with new checksum and git tag values
        run: |
          # update tag with latest version
          
          sed -i "s/.*pkgver=.*/pkgver=${{ inputs.version }}/" PKGBUILD
      - name: Change permissions of build directory
        run: chown -R builduser:builduser .
      - name: Generate package checksum
        run: sudo -u builduser bash -c 'makepkg -g >> PKGBUILD'
      - name: Build package
        run: |
          sudo -u builduser bash -c 'makepkg -s'
          zst_file=$(find -name "*.zst*")
          publish_filename=lightly-${{ inputs.version }}-x86_64.pkg.zst
          mv "$zst_file" $publish_filename
          echo "ZST_ASSET=$publish_filename" >> "$GITHUB_ENV"
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ZST_ASSET }}

